# Importing data and libraries.

In [2]:
import pandas as pd
import numpy as np

In [3]:
data_raw=pd.read_csv('/content/data_num.csv',index_col=0)
data_raw

Age  Pclass  SibSp  Parch      Fare  Sex  Embarked Cherbourg  \
0     22.0       3      1      0    7.2500    0                   0   
1     38.0       1      1      0   71.2833    1                   1   
2     26.0       3      0      0    7.9250    1                   0   
3     35.0       1      1      0   53.1000    1                   0   
4     35.0       3      0      0    8.0500    0                   0   
...    ...     ...    ...    ...       ...  ...                 ...   
1304   NaN       3      0      0    8.0500    0                   0   
1305  39.0       1      0      0  108.9000    1                   1   
1306  38.5       3      0      0    7.2500    0                   0   
1307   NaN       3      0      0    8.0500    0                   0   
1308   NaN       3      1      1   22.3583    0                   1   

      Embarked Queenstown  Embarked Southampton  Crew  Royal  Married women  \
0                       0                     1     0      0              0   
1                       0                     0     0      0              1   
2                       0                     1     0      0              0   
3                       0                     1     0      0              1   
4                       0                     1     0      0              0   
...                   ...                   ...   ...    ...            ...   
1304                    0                     1     0      0              0   
1305                    0                     0     0      0              0   
1306                    0                     1     0      0              0   
1307                    0                     1     0      0              0   
1308                    0                     0     0      0              0   

      Single women  Heir  Men  Survived  \
0                0     0    1       0.0   
1                0     0    0       1.0   
2                1     0    0       1.0   
3                0     0    0       1.0   
4                0     0    1       0.0   
...            ...   ...  ...       ...   
1304             0     0    1       NaN   
1305             0     0    0       NaN   
1306             0     0    1       NaN   
1307             0     0    1       NaN   
1308             0     1    0       NaN   

                                                   Name  
0                               Braund, Mr. Owen Harris  
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                                Heikkinen, Miss. Laina  
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                              Allen, Mr. William Henry  
...                                                 ...  
1304                                 Spector, Mr. Woolf  
1305                       Oliva y Ocana, Dona. Fermina  
1306                       Saether, Mr. Simon Sivertsen  
1307                                Ware, Mr. Frederick  
1308                           Peter, Master. Michael J  

[1309 rows x 17 columns]

# Cleaning

Some file cleaning has already been done previously

Dropping items that will not be used in the analysis

In [4]:
data = data_raw.copy()
data.drop(["Name","Survived"],inplace=True,axis=1)
data.dropna(inplace=True)
print(data.isna().sum())
print(len(data))

Age                     0
Pclass                  0
SibSp                   0
Parch                   0
Fare                    0
Sex                     0
Embarked Cherbourg      0
Embarked Queenstown     0
Embarked Southampton    0
Crew                    0
Royal                   0
Married women           0
Single women            0
Heir                    0
Men                     0
dtype: int64
1046


Separating variables, independent variables X and dependent variable y for split and train

In [5]:
X = data.iloc[:, 1:].values
y = data.iloc[:, 0].values
print(X,y)

[[3. 1. 0. ... 0. 0. 1.]
 [1. 1. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 1. 0. 0.]
 ...
 [3. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 1.]] [22.  38.  26.  ... 28.  39.  38.5]


# Split into training & test sets

The data will be separated into four groups

Independent variables:
- X_train: for train the model
- X_test: for prediction

Dependent variables:
- y_train: for train the model
- y_test: for prediction

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [7]:
np.set_printoptions(threshold=200)
print('---X_train---'*20)
print(X_train)
print('---X_test---'*20)
print(X_test)
print('---y_train---'*20)
print(y_train)
print('---y_test---'*20)
print(y_test)

---X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train---
[[1. 0. 0. ... 0. 0. 1.]
 [3. 1. 0. ... 0. 0. 1.]
 [3. 4. 2. ... 0. 1. 0.]
 ...
 [3. 0. 0. ... 0. 0. 1.]
 [3. 1. 0. ... 0. 0. 1.]
 [1. 1. 1. ... 0. 0. 0.]]
---X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test---
[[3. 0. 0. ... 0. 0. 1.]
 [3. 0. 0. ... 0. 0. 1.]
 [3. 0. 0. ... 1. 0. 0.]
 ...
 [2. 0. 0. ... 1. 0. 0.]
 [2. 1. 0. ... 0. 0. 1.]
 [2. 0. 0. ... 0. 0. 0.]]
---y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y_train------y

#Scaling


.fit() Calculate the mean and standard deviation to use on transform(), and store the values in the StandardScaler() class instance, in this case in the variable sc

.transform() perform standardization by the following formula:
$\mathrm{x}_{standardization}^{}=\frac{x-mean}{standard\text{ }deviation}$

----------------------------

print(sc.mean_) to see the mean 

print(sc.var_) to see the variance

print(np.sqrt(sc.var_)) or print(sc.scale_) to see the standard deviation

-----------------------------

The dummy variables aren't standardized because they are already between 0 and 1

----------------------------

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

from https://www.atoti.io/articles/when-to-perform-a-feature-scaling/ about using scale for tree based machine learning:

"The decision tree splits a node on a feature that increases the homogeneity of the node. This split on a feature is not influenced by other features. Hence, there is virtually no effect of the remaining features on the split. This is what makes them invariant to the scale of the features."

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,:-10] = sc.fit_transform(X_train[:,:-10])
X_test[:,:-10] = sc.transform(X_test[:,:-10])

In [9]:
print('---X_train---'*20)
print(X_train)
print('---X_test---'*20)
print(X_test)

---X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train------X_train---
[[-1.45764509 -0.53869923 -0.49240826 ...  0.          0.
   1.        ]
 [ 0.92474259  0.57603482 -0.49240826 ...  0.          0.
   1.        ]
 [ 0.92474259  3.92023696  1.95790903 ...  0.          1.
   0.        ]
 ...
 [ 0.92474259 -0.53869923 -0.49240826 ...  0.          0.
   1.        ]
 [ 0.92474259  0.57603482 -0.49240826 ...  0.          0.
   1.        ]
 [-1.45764509  0.57603482  0.73275039 ...  0.          0.
   0.        ]]
---X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test------X_test---
[[ 0.92474259 -0.53869923 -0.49240826 ...  0.         

# Modelling

## Build the model

Instantiate the object with the name regressor as a model, for the machine learning

In [10]:
from sklearn.ensemble import RandomForestRegressor
from sklearn import linear_model


parameters = {'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 3, 'n_estimators': 150 }

regressor = RandomForestRegressor(**parameters, random_state=0)

## Train the model

Train the model on classifier object, with X_train and y_train

In [11]:
regressor.fit(X_train, y_train)

RandomForestRegressor(max_depth=6, max_features='sqrt', min_samples_split=3,
                      n_estimators=150, random_state=0)

## Make predictions

Predictions for dependent variables with the trained model

Prediction for the vector X_test

In [12]:
prediction = regressor.predict(X_test)
np.set_printoptions(precision=2)
print(prediction)

[28.83 28.59 24.06 ... 27.38 33.43 40.33]


# Evaluation

 R²(coefficient of determination) regression score function.

Best possible score is 1.0 and it can be negative (because the model can be arbitrarily worse). In the general case when the true y is non-constant, a constant model that always predicts the average y disregarding the input features would get a R² score of 0.0.

Source: https://scikit-learn.org/stable/modules/generated/sklearn.metrics.r2_score.html

In [13]:
from sklearn.metrics import r2_score
r2_score(y_test, prediction)

0.37066725023375624

##Calculating the best parameter for the model

Shows every parameter that could be use on GridSearchCV for this kind of machine learning

In [14]:
print(RandomForestRegressor().get_params().keys())

dict_keys(['bootstrap', 'ccp_alpha', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'max_samples', 'min_impurity_decrease', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'n_estimators', 'n_jobs', 'oob_score', 'random_state', 'verbose', 'warm_start'])


GridSearchCV calculates the best parameter for the model.

First you calculate using GridSearchCV, then use the values on your model, lastly you disable the algorithm of GridSearchCV by commenting

It could be divided in parts because it is time expensive

In [15]:
#Calculating the best model possible
# This code could take a long time, uncoment to run the full GridSearchCV
'''
from sklearn.model_selection import GridSearchCV 

#Parameters
#1° attempt Best result: 0.459258 using {'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 3, 'n_estimators': 200}
parameters = {'n_estimators': list(range(100,300,100)), 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': list(range(2,8,2)),'min_samples_split': list(range(2,8,1))}

#2° attempt Best result: 0.461001 using {'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 3, 'n_estimators': 150}
parameters = {'n_estimators': list(range(150,250,50)), 'max_features': ['sqrt'], 'max_depth': list(range(5,7,1)),'min_samples_split': [3]}

#GridSearchCV
estimator = RandomForestRegressor()
grid = GridSearchCV(estimator,parameters, cv=None)
grid.fit(X_train, y_train)
print("Best result: %f using %s" % (grid.best_score_, grid.best_params_))
'''


Best result: 0.457491 using {'max_depth': 6, 'max_features': 'sqrt', 'min_samples_split': 3, 'n_estimators': 150}


# Predicting Age

Checking NaN

In [16]:
data_age = data_raw.copy()
data_age.isna().sum()

Age                     263
Pclass                    0
SibSp                     0
Parch                     0
Fare                      0
Sex                       0
Embarked Cherbourg        0
Embarked Queenstown       0
Embarked Southampton      0
Crew                      0
Royal                     0
Married women             0
Single women              0
Heir                      0
Men                       0
Survived                418
Name                      0
dtype: int64

Predicting and changing the age value in data_age

In [17]:
age = []
import math
for i ,v in data_age.iterrows():
  if math.isnan(v['Age']):
    X_prediction = v[1:-2].values
    X_prediction[:-10] = sc.transform(X_prediction[:-10].reshape(1, -1))
    prediction = regressor.predict(X_prediction.reshape(1, -1))
    data_age.iloc[i, data_age.columns.get_loc('Age')] = prediction[0]
    #print(i, v)
    age.append(prediction[0])

Checking

In [18]:
print(np.mean(age))
age

29.328134823118653


[32.88503992014068,
 31.26594283280021,
 32.21437376337456,
 28.968690540036356,
 23.883626853042163,
 28.588426511371928,
 39.822118762333425,
 23.808285722437876,
 28.96765375890849,
 29.12856898481872,
 28.588426511371928,
 33.21166468284366,
 23.808285722437876,
 26.978524963613072,
 40.8198899492217,
 41.17598057562798,
 6.992908972366625,
 28.588426511371928,
 28.588426511371928,
 23.808285722437876,
 28.588426511371928,
 28.588426511371928,
 28.588426511371928,
 28.588426511371928,
 21.454106128955075,
 28.588426511371928,
 33.041387729928765,
 9.90054302880418,
 29.51859928597028,
 28.704315425153794,
 28.537202166535394,
 10.893611128154172,
 44.46059827121882,
 40.823607788388806,
 4.9167463619675456,
 12.766339407017869,
 31.055351897346153,
 40.47865972548702,
 31.452415368309442,
 33.041387729928765,
 23.808285722437876,
 22.87489608549305,
 32.472158901592614,
 28.588426511371928,
 8.330205325360748,
 23.792646160402555,
 20.28248611580972,
 21.367045652607654,
 28.704315

In [19]:
data_age

Age  Pclass  SibSp  Parch      Fare  Sex  Embarked Cherbourg  \
0     22.000000       3      1      0    7.2500    0                   0   
1     38.000000       1      1      0   71.2833    1                   1   
2     26.000000       3      0      0    7.9250    1                   0   
3     35.000000       1      1      0   53.1000    1                   0   
4     35.000000       3      0      0    8.0500    0                   0   
...         ...     ...    ...    ...       ...  ...                 ...   
1304  28.588427       3      0      0    8.0500    0                   0   
1305  39.000000       1      0      0  108.9000    1                   1   
1306  38.500000       3      0      0    7.2500    0                   0   
1307  28.588427       3      0      0    8.0500    0                   0   
1308   6.619443       3      1      1   22.3583    0                   1   

      Embarked Queenstown  Embarked Southampton  Crew  Royal  Married women  \
0                       0                     1     0      0              0   
1                       0                     0     0      0              1   
2                       0                     1     0      0              0   
3                       0                     1     0      0              1   
4                       0                     1     0      0              0   
...                   ...                   ...   ...    ...            ...   
1304                    0                     1     0      0              0   
1305                    0                     0     0      0              0   
1306                    0                     1     0      0              0   
1307                    0                     1     0      0              0   
1308                    0                     0     0      0              0   

      Single women  Heir  Men  Survived  \
0                0     0    1       0.0   
1                0     0    0       1.0   
2                1     0    0       1.0   
3                0     0    0       1.0   
4                0     0    1       0.0   
...            ...   ...  ...       ...   
1304             0     0    1       NaN   
1305             0     0    0       NaN   
1306             0     0    1       NaN   
1307             0     0    1       NaN   
1308             0     1    0       NaN   

                                                   Name  
0                               Braund, Mr. Owen Harris  
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                                Heikkinen, Miss. Laina  
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                              Allen, Mr. William Henry  
...                                                 ...  
1304                                 Spector, Mr. Woolf  
1305                       Oliva y Ocana, Dona. Fermina  
1306                       Saether, Mr. Simon Sivertsen  
1307                                Ware, Mr. Frederick  
1308                           Peter, Master. Michael J  

[1309 rows x 17 columns]

In [20]:
data_age.isna().sum()

Age                       0
Pclass                    0
SibSp                     0
Parch                     0
Fare                      0
Sex                       0
Embarked Cherbourg        0
Embarked Queenstown       0
Embarked Southampton      0
Crew                      0
Royal                     0
Married women             0
Single women              0
Heir                      0
Men                       0
Survived                418
Name                      0
dtype: int64

# Downloading Data. Exporting data for Machine Learning analysis.

To export the data, delete the # in command: **#files.download('output.csv')**

In [21]:
from google.colab import files
data_age.to_csv('data_for_survived.csv', encoding = 'utf-8-sig') 
files.download('data_for_survived.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [22]:
data_age

Age  Pclass  SibSp  Parch      Fare  Sex  Embarked Cherbourg  \
0     22.000000       3      1      0    7.2500    0                   0   
1     38.000000       1      1      0   71.2833    1                   1   
2     26.000000       3      0      0    7.9250    1                   0   
3     35.000000       1      1      0   53.1000    1                   0   
4     35.000000       3      0      0    8.0500    0                   0   
...         ...     ...    ...    ...       ...  ...                 ...   
1304  28.588427       3      0      0    8.0500    0                   0   
1305  39.000000       1      0      0  108.9000    1                   1   
1306  38.500000       3      0      0    7.2500    0                   0   
1307  28.588427       3      0      0    8.0500    0                   0   
1308   6.619443       3      1      1   22.3583    0                   1   

      Embarked Queenstown  Embarked Southampton  Crew  Royal  Married women  \
0                       0                     1     0      0              0   
1                       0                     0     0      0              1   
2                       0                     1     0      0              0   
3                       0                     1     0      0              1   
4                       0                     1     0      0              0   
...                   ...                   ...   ...    ...            ...   
1304                    0                     1     0      0              0   
1305                    0                     0     0      0              0   
1306                    0                     1     0      0              0   
1307                    0                     1     0      0              0   
1308                    0                     0     0      0              0   

      Single women  Heir  Men  Survived  \
0                0     0    1       0.0   
1                0     0    0       1.0   
2                1     0    0       1.0   
3                0     0    0       1.0   
4                0     0    1       0.0   
...            ...   ...  ...       ...   
1304             0     0    1       NaN   
1305             0     0    0       NaN   
1306             0     0    1       NaN   
1307             0     0    1       NaN   
1308             0     1    0       NaN   

                                                   Name  
0                               Braund, Mr. Owen Harris  
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  
2                                Heikkinen, Miss. Laina  
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  
4                              Allen, Mr. William Henry  
...                                                 ...  
1304                                 Spector, Mr. Woolf  
1305                       Oliva y Ocana, Dona. Fermina  
1306                       Saether, Mr. Simon Sivertsen  
1307                                Ware, Mr. Frederick  
1308                           Peter, Master. Michael J  

[1309 rows x 17 columns]